2022-11-25 14:35:57,987 INFO    MainThread:36349 [wandb_setup.py:_flush():68] Configure stats pid to 36349
2022-11-25 14:35:57,988 INFO    MainThread:36349 [wandb_setup.py:_flush():68] Loading settings from /Users/slavapirogov/.config/wandb/settings
2022-11-25 14:35:57,988 INFO    MainThread:36349 [wandb_setup.py:_flush():68] Loading settings from /Users/slavapirogov/fastspeech2/wandb/settings
2022-11-25 14:35:57,988 INFO    MainThread:36349 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-25 14:35:57,988 INFO    MainThread:36349 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/Users/slavapirogov/fastspeech2/train.py'}
2022-11-25 14:35:57,988 INFO    MainThread:36349 [wandb_init.py:_log_setup():476] Logging user logs to /Users/slavapirogov/fastspeech2/wandb/run-20221125_143557-ikdziu03/logs/debug.log
2022-11-25 14:35:57,989 INFO    MainThread:36349 [wandb_init.py:_log_setup():477] Logging internal logs to /Users/slavapirogov/fastspeech2/wandb/run-20221125_143557-ikdziu03/logs/debug-internal.log
2022-11-25 14:35:57,989 INFO    MainThread:36349 [wandb_init.py:init():516] calling init triggers
2022-11-25 14:35:57,990 INFO    MainThread:36349 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-25 14:35:57,990 INFO    MainThread:36349 [wandb_init.py:init():569] starting backend
2022-11-25 14:35:57,990 INFO    MainThread:36349 [wandb_init.py:init():573] setting up manager
2022-11-25 14:35:57,998 INFO    MainThread:36349 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-11-25 14:35:58,005 INFO    MainThread:36349 [wandb_init.py:init():580] backend started and connected
2022-11-25 14:35:58,011 INFO    MainThread:36349 [wandb_init.py:init():658] updated telemetry
2022-11-25 14:35:58,059 INFO    MainThread:36349 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-25 14:36:01,132 WARNING MsgRouterThr:36349 [router.py:message_loop():77] message_loop has been closed
2022-11-25 14:36:08,118 ERROR   MainThread:36349 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/Users/slavapirogov/.conda/envs/PyTorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/Users/slavapirogov/.conda/envs/PyTorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/Users/slavapirogov/.conda/envs/PyTorch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
