2022-11-25 14:39:52,191 INFO    MainThread:36397 [wandb_setup.py:_flush():68] Configure stats pid to 36397
2022-11-25 14:39:52,192 INFO    MainThread:36397 [wandb_setup.py:_flush():68] Loading settings from /Users/slavapirogov/.config/wandb/settings
2022-11-25 14:39:52,192 INFO    MainThread:36397 [wandb_setup.py:_flush():68] Loading settings from /Users/slavapirogov/fastspeech2/wandb/settings
2022-11-25 14:39:52,192 INFO    MainThread:36397 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-25 14:39:52,193 INFO    MainThread:36397 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/Users/slavapirogov/fastspeech2/train.py'}
2022-11-25 14:39:52,193 INFO    MainThread:36397 [wandb_init.py:_log_setup():476] Logging user logs to /Users/slavapirogov/fastspeech2/wandb/run-20221125_143952-2scm1rag/logs/debug.log
2022-11-25 14:39:52,194 INFO    MainThread:36397 [wandb_init.py:_log_setup():477] Logging internal logs to /Users/slavapirogov/fastspeech2/wandb/run-20221125_143952-2scm1rag/logs/debug-internal.log
2022-11-25 14:39:52,194 INFO    MainThread:36397 [wandb_init.py:init():516] calling init triggers
2022-11-25 14:39:52,195 INFO    MainThread:36397 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-25 14:39:52,196 INFO    MainThread:36397 [wandb_init.py:init():569] starting backend
2022-11-25 14:39:52,196 INFO    MainThread:36397 [wandb_init.py:init():573] setting up manager
2022-11-25 14:39:52,202 INFO    MainThread:36397 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-11-25 14:39:52,210 INFO    MainThread:36397 [wandb_init.py:init():580] backend started and connected
2022-11-25 14:39:52,215 INFO    MainThread:36397 [wandb_init.py:init():658] updated telemetry
2022-11-25 14:39:52,265 INFO    MainThread:36397 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-25 14:39:55,351 WARNING MsgRouterThr:36397 [router.py:message_loop():77] message_loop has been closed
2022-11-25 14:40:02,324 ERROR   MainThread:36397 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/Users/slavapirogov/.conda/envs/PyTorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/Users/slavapirogov/.conda/envs/PyTorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/Users/slavapirogov/.conda/envs/PyTorch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
